
kind: Namespace
apiVersion: v1
metadata:
  name: java-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  labels:
    app: java-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice
        image: tftest/java-microservice
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-microservice
spec:
  selector:
    app: java-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: java-microservice
  namespace: java-microservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  tls:
    - hosts:
        - java-microservice.com
  rules:
    - host: java-microservice.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: java-microservice
              servicePort: 8080