
kind: Namespace
apiVersion: v1
metadata:
  name: java-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  labels:
    app: java-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice
        image: tftest/java-microservice
        ports:
        - containerPort: 8080